version: '3'

volumes:
  postgres-data:
    driver: local

services:
  petshop:
    build:
      context: ./
    container_name: petshop
    env_file:
      - ./.env
    volumes:
       - ./:/app
    ports:
      - '8000:8000'
  db:
    image: postgres
    container_name: petshop-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: 
      ./.env
    environment:
       PGDATA: /var/lib/postgresql/data/pgdata
       POSTGRES_DB: ${TYPEORM_DATABASE}
       POSTGRES_USER: ${TYPEORM_USERNAME}
       POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
    ports:
      - 5434:5432
    restart: on-failure


